[server]
port=1234

[psql]
ssl_mode="disable"
database="exercise_parser"
user="exercise"
password="parser"
host="localhost"
port=5432
logging=false

[migration]
dir="migrations"

[resources.dir]
exercises="resources/exercises"
lemmas="resources/lemmas"
related_names="resources/related_names"
related_searches_bing="resources/related_searches_bing"
related_searches_goog="resources/related_searches_goog"
stop_words="resources/stop_words"

[parser]
stop_phrases="resources/parser/stop_phrases.txt"

[middleware]
auth=false

[auth.apple]
client_id="___CLIENT_ID___"
team_id="___TEAM_ID___"
key_id="___KEY_ID___"
base64_key_p8="___APPLE_BASE64_KEY_P8___"
redirect_uri="http://localhost:3000"

[auth.pem]
base64_keypair="LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBNjJVSDkyZ2dlY1JFK1VTNERpczJCOWFJblNCem5MQlJuam5PTHJmQ1BEVEFnRVRiClJzTk5VRHc0NmllZHhrcHVnTmNPYXBqOU1JbnhYZTlNZ3BiNFAvUHFJS2p1TzE3eHlZaXJrZ0dOQXRzb3loMGcKd3FlM0srVE45alVZTlNJdVFqTmdpRkRuN0UxWkxuRmZuaWFRV1pPMXdkdzdUeml2TW16RFpDYjFFWHdOZUI4dwpPU1NRb3dia3IrOFMzSERWTUwxWDJKdGF3WUVieDJQV3hIc1VPMkpaZTFBU1ZQQWFQZktxOS9hUFoxR2VRVXBjCm1ldlMvdnhIM0k3SlROUkg3S2xkNE5wQjl4dU5Ya1BZQzgxeEU0ZkF6bGYxRnNRT0VZNHZiMmNCZlcrZDkzRzEKNk1hckx1SzY3K2grVzJtVlBxNEllUGRzU2FBY0VaOTZKNEFkSHdJREFRQUJBb0lCQUgxSjN2MmVISHJ6TGtzRwplbmlBSTFmMHBlNEwwYjA2VTViRjZhb1FBSUFQQzg2NTE0UklleVFUaWErSHVvQktLWnJGM0ZSOGJYYWlWU2ZNCk1JcnBVK1NtTEoySmpKTnBLNFE3RENiQVVJK09tcDFJOTZEanA2ampOWVN3S2R4Ti94VVpSMjRHc2dxaCtLK3gKaEZVbTdYbmdGc1BDTm9jcUFvWHlRZVZTbnVuWWVjRnRQOXZnZ0RlWWd1Y3dmaXBTblFFVTZKN3VHNXFlZXJxQgpBemkxYmpGMFBZbUJZeTRDTElRNFVOeWtYV05MTHJUUi9ZKzNBcVliUHdybEJqQTBIRnlIbUd5Q1FmRktrMS9RCkI0a3BhbWZ2djdxS1JPdUZuQTl2RGtTWDhVaE9rVE1rd0tJNDdEMmNYZWFxbFJNcDZKS2V3QTYxZEI1dmt6eDkKZTcvN25oRUNnWUVBLzdtdVpYTGdDMDZxL0lPNGxPVUpEK2h0eldEaytjUGZybjdCVk01VDhHSFFWZ2V4dUVvaApDd2V5VzdkUlV1dFljOVczTUV1RGYzNGRJNHdMZVBnUUlOSzdiSW5UeXkvcXp3dVM5WUtSMGZFSTdpVVlZSVBWClUrOTdCSWYwVUFlS0F6QVdGZFpraDQ0YTNycVpjT0ZXd0dzVFlhd1hDYkR4VFBnamJEb3NLUE1DZ1lFQTY2WEMKYUViRmUwWTd2bDh0OUVQOVg5UjQzSjgwcWpxYVJNOGh1WEpXMG9xb2J5eis0bUJmT1RQMGtCZlltL2V3d2tQRApUTFB5TlkxT0F1K0JVd1hhMDRGSzY5VzhaU3J3VFVqUkp1MVVqRko5MDhaSUZUcUprYWgxZjRMUVQ0NWFCUmdTCnFZdnpSYnhtZlZKYVpwTVQ1NkFURFBwdEZUcXNFUXd1VlJOVmhpVUNnWUVBdUhHUGxNSmZVQ2lFY1M3OFlnQTAKSWhJdHFEVmIwYjN5UnFSTUEwUHlETzR2MnUwZnhPRktwZTcrT09LbXVGemc1bU5lQm1wZ3hRTU1OMGhhT2YwSgpmUE1obGE1dllSMEZpaUk1OC9RaUFyK01CbUFoRGZQb1dPcmcycXJJanpSdzJjM0VFQ29iUmg0N3lTdmpZaVJWCmN1R0lFQ21VVUR3Y1ByeTJwK2ZwVS9zQ2dZRUFzZ3ViR01pb08xMDBsTUU3YW56WWUwaUJUVWlwTlJsMEtCdE0KZ3Q2bVJRdm8rWjlJc2VoWTZsS2NMU2NuVGFqWEQrQzlOajRiK21SYWxoTTZabTFkQ2tOOVJUVkgxRFNlUGZhUAp1TmJHOUFMNytUK3VoUU9tbjd4bGtzTlcrMVUySlBVc1hKaFdaZEZVcXNuSGJnc2dsZmkzakMzR3I2eVdCNGRwCmxuUTJRVlVDZ1lBZzZuNjlweWJMWjltK1VpVC92WHNsNEYzMnErV2VBZCtlZGRJRUphL2QrZXpEY3R5ZTdVb3kKVk5wbGJXNTVReU5lT0lVR3Q1eVhFSVl2TWlnRGtZZURKQ2wwWmJYVUgvQjU3MGVPekQxMEljdnFkQm1aUWtqWQptekhBYUNkd3JvdlJWemhGMmVRNys1UE9rSmtINjMvQWRvUHJuMXRISTdSVjhzd2p4WlpDbFE9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo="

[logging]
base_dir="output"

[backup.s3]
bucket="ryden-resources"
region="us-east-2"
related_names_key_name="backup/related_names" 

[images]
storage_type="file"
[images.file]
user_image_dir="resources/.cache/images/user"
