[server]
port=1234

[psql]
ssl_mode="disable"
database="exercise_parser"
user="exercise"
password="parser"
host="localhost"
port=5432

[resources.dir]
exercises="resources/exercises"
lemmas="resources/lemmas"
related_names="resources/related_names"
related_searches_bing="resources/related_searches_bing"
related_searches_goog="resources/related_searches_goog"
stop_words="resources/stop_words"

[middleware]
auth=false

[auth.apple]
client_id="___CLIENT_ID___"
team_id="___TEAM_ID___"
key_id="___KEY_ID___"
base64_key_p8="___APPLE_BASE64_KEY_P8___"
redirect_uri="localhost:3000"

[auth.pem]
base64_keypair="LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBM1kxVGFHaFpEd0tmT3FMUTcveFZZOU5Bd2h1NStUSXZSS09LZVR3K2w1YTgyMG85CmVIbktIQU5RMG9LZEZkMFJrSzZYVlJlcUkrVWpYZXJNUnFaNnU3M1didEptS3dUUlUvWHVFUUUxMWxidkhQSDQKcHNMYzJRdG44N2pCbFJpMmczc254eWFrTkhUM1N1K2dIM2dFWXlNMVdoWGlVV3JsWW9GcG9VbXlKek4xeXkyZQpSY21kV21Bbi9IRyt3RnJoS3pKTDJnVXh4eDZUSjJIR0VBUjBhUVlLMTZBblk2eFYwaXFDM3NmZVpEc0tmWWE5CitNUEZORUIrUnkwdlpnVXE5THA2dFQ3S0FUaHdKb1NVWHhLY3lVYUlFeXQ0S09vcDVyVnEvOGRGN0p2a0ZWMnEKeXVsWDJCTStQN01JeWVlTmFlYmd1VDV6R1NLSXVtWCtQYk13UHdJREFRQUJBb0lCQVFDMGx2b2g1TXlUTzZQbQorOGdybGhkVVkySXAxc2ZrcEU5N040TXNCenROL1FTOEN1dklSQjNHYjcxMW1obkpOSVdZMVhkdFdQaktnWUF1CmtiRW85WktkYmNSWVdSQUdpTXJJRVhLWVVkQThnbWd0dzk3V3I0ZXRNMnJzY3ZENFEwaWlLOFRreEU2Y282cmYKWGl1Nit1MDRrZjV2QzkrS1ZnUGNJM2lpaTV1Mzd1b1dSZ3pjS3hZVTlUQkpJcUJGajlyVFdYUkFLa0RuMmVMcgpJYVVlTllKQXpPRWNtd1lWRG1XRVczUkZzTHNpWlNNRWlCUTFyb1NlT2lLbEtEQkhLakdZaW02ck1zWWdnWFZLCnYvRjZlN3d0MnhOTXd4aUFNQzhLelJSQ3p1MTZ0V3dtdms1ZWJFaW94ZHBjcUtKc2tvU3duRjZTeTR0QllndU4KNkZRUUlDVGhBb0dCQU8vL1g5d25XMXlWRmhDZDZFWDhob01nSnFRZHA5RklYVFY0b0RFZ3NIUHVQMlM3RERtcgpqV2ZZRHh0eFFPdk03aTc1U0lDU0pyL3o4Z09NVjZzRVVaSE42VGhDeTNIQm1oRSt1WC8vdTY5VHFEUmZRbWlhCno0R0Z3OStEYlhRZUZhQTUvMXVZYWZ4TCt3Yzlsdk1nUVFwaUxodHBidzJVdVA3VzBNUlU0QTlWQW9HQkFPeFQKR01vUU5TaEt0VWNNM1I0c0RNeHd2Q1VOMGdPbWVwNmZNRGtpelpaeUU5VXAvdElGRk5xR3pUL2xiR242a3d3TApTc0RvN2Vic0tVbWtUQXpud2JQdnc2d3huVlphcitIbmhOenNxbW9SaXAyb0w4NlRmTCtZMXQzSE5ZZ1RVNlZGCnI2MEJrTno0WXZWWHg3VXVHa2tnRDZYY0UrQ0U4Vmh1LzUrQWtIbERBb0dBTVhLOWpuK3hiRWJ2YitjSkYzcHIKUUpNY1F3NDFLSUt2YWJmNzBZTjV0N2tyNkpZOWM1aHNIeXcrR0pwaUZQTjVVOFphOE5xc0R6cTA3NVEzNysySQozUEMvRDY5N2VXbTVVN3BId0I2eHpmTC9vaUxLYlFFUXBoQW9obUh1NkZEV2hkZk5URkwvNjFMQVd3S09tbk5YCjAwcmRVeHFMSGhJNWQ1Qk5IVmFiZjYwQ2dZQTBqNGJENmpib2J6VkNTQ29sdThaYzhmWG1oOXhkMDNrU0xuV2IKUDVKYUU2VTFrOUdKQkhoTzRneGtXYkp6SDdmMHhjNHFlYVB2NkRhR21uUVBxcnY2T1NsYjh1ejdkOUFHZm1lZQplMFNyc3BzUjFZWk1lNkVUTy9zTitIQi9nMHpuUlVoOVFndm1HWmhvMk0waURzN3AxS2VtUy94Znd6R3FhWVdSCkJCY2Q0UUtCZ0VweFJFVk44aWdncnBJMHUxa01zL2crcE5vQUlWNVZ1RjIyY2NNSHB3SThGejBiWFBkbmZRcUsKY0pBejZYV085Wkh6TzY4ZitHNjZEN1M0TXB4NU1FVGdwM21SeTdDNGpBbW9LNUpSWHZvWXhzbmhmMklpUTVPdAp3djlraFlkQWdVSVRjTXJMdEhtUWd3N1FKVWwwVFp3N2RpSmo3TE8vbG4vQ2pYTHZqWnByCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg=="
