[server]
port=1234

[psql]
ssl_mode="disable"
database="exercise_parser"
user="exercise"
password="parser"
host="localhost"
port=5432

[resources.dir]
exercises="resources/exercises"
lemmas="resources/lemmas"
related_names="resources/related_names"
related_searches_bing="resources/related_searches_bing"
related_searches_goog="resources/related_searches_goog"
stop_words="resources/stop_words"

[middleware]
auth=false

[auth.apple]
client_id="ryden.web"
key_p8="____APPLE_KEY_P8___"

[auth.pem]
base64_keypair = """
LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVB
M1kxVGFHaFpEd0tmT3FMUTcveFZZOU5Bd2h1NStUSXZSS09LZVR3K2w1YTgyMG85
CmVIbktIQU5RMG9LZEZkMFJrSzZYVlJlcUkrVWpYZXJNUnFaNnU3M1didEptS3dU
UlUvWHVFUUUxMWxidkhQSDQKcHNMYzJRdG44N2pCbFJpMmczc254eWFrTkhUM1N1
K2dIM2dFWXlNMVdoWGlVV3JsWW9GcG9VbXlKek4xeXkyZQpSY21kV21Bbi9IRyt3
RnJoS3pKTDJnVXh4eDZUSjJIR0VBUjBhUVlLMTZBblk2eFYwaXFDM3NmZVpEc0tm
WWE5CitNUEZORUIrUnkwdlpnVXE5THA2dFQ3S0FUaHdKb1NVWHhLY3lVYUlFeXQ0
S09vcDVyVnEvOGRGN0p2a0ZWMnEKeXVsWDJCTStQN01JeWVlTmFlYmd1VDV6R1NL
SXVtWCtQYk13UHdJREFRQUJBb0lCQVFDMGx2b2g1TXlUTzZQbQorOGdybGhkVVky
SXAxc2ZrcEU5N040TXNCenROL1FTOEN1dklSQjNHYjcxMW1obkpOSVdZMVhkdFdQ
aktnWUF1CmtiRW85WktkYmNSWVdSQUdpTXJJRVhLWVVkQThnbWd0dzk3V3I0ZXRN
MnJzY3ZENFEwaWlLOFRreEU2Y282cmYKWGl1Nit1MDRrZjV2QzkrS1ZnUGNJM2lp
aTV1Mzd1b1dSZ3pjS3hZVTlUQkpJcUJGajlyVFdYUkFLa0RuMmVMcgpJYVVlTllK
QXpPRWNtd1lWRG1XRVczUkZzTHNpWlNNRWlCUTFyb1NlT2lLbEtEQkhLakdZaW02
ck1zWWdnWFZLCnYvRjZlN3d0MnhOTXd4aUFNQzhLelJSQ3p1MTZ0V3dtdms1ZWJF
aW94ZHBjcUtKc2tvU3duRjZTeTR0QllndU4KNkZRUUlDVGhBb0dCQU8vL1g5d25X
MXlWRmhDZDZFWDhob01nSnFRZHA5RklYVFY0b0RFZ3NIUHVQMlM3RERtcgpqV2ZZ
RHh0eFFPdk03aTc1U0lDU0pyL3o4Z09NVjZzRVVaSE42VGhDeTNIQm1oRSt1WC8v
dTY5VHFEUmZRbWlhCno0R0Z3OStEYlhRZUZhQTUvMXVZYWZ4TCt3Yzlsdk1nUVFw
aUxodHBidzJVdVA3VzBNUlU0QTlWQW9HQkFPeFQKR01vUU5TaEt0VWNNM1I0c0RN
eHd2Q1VOMGdPbWVwNmZNRGtpelpaeUU5VXAvdElGRk5xR3pUL2xiR242a3d3TApT
c0RvN2Vic0tVbWtUQXpud2JQdnc2d3huVlphcitIbmhOenNxbW9SaXAyb0w4NlRm
TCtZMXQzSE5ZZ1RVNlZGCnI2MEJrTno0WXZWWHg3VXVHa2tnRDZYY0UrQ0U4Vmh1
LzUrQWtIbERBb0dBTVhLOWpuK3hiRWJ2YitjSkYzcHIKUUpNY1F3NDFLSUt2YWJm
NzBZTjV0N2tyNkpZOWM1aHNIeXcrR0pwaUZQTjVVOFphOE5xc0R6cTA3NVEzNysy
SQozUEMvRDY5N2VXbTVVN3BId0I2eHpmTC9vaUxLYlFFUXBoQW9obUh1NkZEV2hk
Zk5URkwvNjFMQVd3S09tbk5YCjAwcmRVeHFMSGhJNWQ1Qk5IVmFiZjYwQ2dZQTBq
NGJENmpib2J6VkNTQ29sdThaYzhmWG1oOXhkMDNrU0xuV2IKUDVKYUU2VTFrOUdK
QkhoTzRneGtXYkp6SDdmMHhjNHFlYVB2NkRhR21uUVBxcnY2T1NsYjh1ejdkOUFH
Zm1lZQplMFNyc3BzUjFZWk1lNkVUTy9zTitIQi9nMHpuUlVoOVFndm1HWmhvMk0w
aURzN3AxS2VtUy94Znd6R3FhWVdSCkJCY2Q0UUtCZ0VweFJFVk44aWdncnBJMHUx
a01zL2crcE5vQUlWNVZ1RjIyY2NNSHB3SThGejBiWFBkbmZRcUsKY0pBejZYV085
Wkh6TzY4ZitHNjZEN1M0TXB4NU1FVGdwM21SeTdDNGpBbW9LNUpSWHZvWXhzbmhm
MklpUTVPdAp3djlraFlkQWdVSVRjTXJMdEhtUWd3N1FKVWwwVFp3N2RpSmo3TE8v
bG4vQ2pYTHZqWnByCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
"""
