[server]
port=1234

[psql]
ssl_mode=""
database=""
user=""
password=""
host=""
port=5432

[resources.dir]
exercises="resources/exercises"
lemmas="resources/lemmas"
related_names="resources/related_names"
related_searches_bing="resources/related_searches_bing"
related_searches_goog="resources/related_searches_goog"
stop_words="resources/stop_words"

[middleware]
auth=true

[auth.apple]
client_id="ryden.web"
key_p8="____APPLE_KEY_P8___"

[auth.pem]
keypair="___PEM___"
