[server]
port=1234

[psql]
ssl_mode="disable"
database=""
user=""
password=""
host=""
port=5432

[resources.dir]
exercises="/go/src/exercise_parser/server/resources/exercises"
lemmas="/go/src/exercise_parser/server/resources/lemmas"
related_names="/go/src/exercise_parser/server/resources/related_names"
related_searches_bing="/go/src/exercise_parser/server/resources/related_searches_bing"
related_searches_goog="/go/src/exercise_parser/server/resources/related_searches_goog"
stop_words="/go/src/exercise_parser/server/resources/stop_words"

[middleware]
auth=true

[auth.apple]
client_id="ryden.web"
base64_key_p8="____APPLE_BASE64_KEY_P8___"

[auth.pem]
base64_keypair="___PEM___"
