[server]
port=1234

[psql]
ssl_mode="disable"
database=""
user=""
password=""
host=""
port=5432
logging=false

[migration]
dir="/go/src/exercise_parser/server/migrations"

[resources.dir]
exercises="/go/src/exercise_parser/server/resources/exercises"
lemmas="/go/src/exercise_parser/server/resources/lemmas"
related_names="/go/src/exercise_parser/server/resources/related_names"
related_searches_bing="/go/src/exercise_parser/server/resources/related_searches_bing"
related_searches_goog="/go/src/exercise_parser/server/resources/related_searches_goog"
stop_words="/go/src/exercise_parser/server/resources/stop_words"

[parser]
stop_phrases="/go/src/exercise_parser/server/resources/parser/stop_phrases.txt"

[middleware]
auth=true

[auth.apple]
client_id="com.rydenapp.web"
team_id="___TEAM_ID___"
key_id="___KEY_ID___"
base64_key_p8="____APPLE_BASE64_KEY_P8___"
redirect_uri="https://rydenapp.com"

[auth.pem]
base64_keypair="___PEM___"

[logging]
base_dir="/var/log/ryden-server"

[backup.s3]
bucket="ryden-resources"
region="us-east-2"
related_names_key_name="backup/related_names" 

[images]
storage_type="s3"
[images.s3]
bucket="ryden-resources"
user_image_key_name="images/user_profile"
