[server]
port=1234

[psql]
sslmode="disable"
database="exercise_parser"
user="exercise"
password="parser"
host="localhost"
port=5432

[resources.dir]
exercises="resources/exercises"
lemmas="resources/lemmas"
related_names="resources/related_names"
related_searches_bing="resources/related_searches_bing"
related_searches_goog="resources/related_searches_goog"
stop_words="resources/stop_words"

[middleware]
auth=true

[auth]
file="resources/dev_rsa_key/keypair.pem"
