[server]
port=1234

[psql]
sslmode="disable"
database="exercise_parser"
user="exercise"
password="parser"
host="localhost"
port=5432

[resources]
exercises_dir="resources/exercises"
lemmas_dir="resources/lemmas"
related_names_dir="resources/related_names"
related_searches_bing_dir="resources/related_searches_bing"
related_searches_goog_dir="resources/related_searches_goog"
