[server]
port=1234

[psql]
sslmode="disable"
database="exercise_parser"
user="exercise"
password="parser"
host="localhost"
port=5432

[resources]
exercises_dir="resources/exercises"
lemmas_dir="resources/lemmas"