on:
  push:
    branches:
      - master
    paths:
      - 'web/console/**'

name: Web Console App Deploy to Amplify

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Deploy
        id: trigger_deploy
        env:
          WEBHOOK_TOKEN: ${{ secrets.WEBHOOK_TOKEN }}
        run: |
          curl -X POST -d {} "https://webhooks.amplify.us-east-2.amazonaws.com/prod/webhooks?id=f040bf02-0f19-4e20-979a-b3e61e4a5a48&token=h3iypOEFj25plFSI32bPKvc2AImr6p7DUIn5XR1nQ&operation=startbuild" -H "Content-Type:application/json"
